<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html>
<head>
<meta name="copyright" content="2000,  Bradley Kjell" />
<meta name="author" content="Bradley Kjell kjell@ieee.org " />
<meta name="robots" content="index,follow" />
<title>Opening the Files</title>
<link rel="stylesheet" type="text/css" href="../CAIstyle.css" />
</head>

<body>
<!-- generated by CSSmaker.java, version of 01/14/2003-->
<!-- from source javaChap86.frames on Tue Jul 15 18:47:31 EDT 2003 -->

<!-- ANSWER AREA -->

<div class="answer">
<h3>A good answer might be:</h3>
<p>
Exceptions may be thrown when the files are opened.
</p>


</div>

<!-- LESSON AREA -->
<div class="lesson">
<h1>Opening the Files</h1>

<p>
The constructors for <code>FileInputStream</code>
and for  <code>FileOutputStream</code> throw exceptions
which need to be caught.
This calls for an outer <code>try{}</code> block:
</p>

<pre class="program">
DataInputStream  instr;
DataOutputStream outstr;
. . . . 
<span style="color:red;font-weight:bold">try
{</span>
  instr = 
    new DataInputStream(
      new BufferedInputStream(
        new FileInputStream( args[0] )));
  
  outstr = 
    new DataOutputStream(
      new BufferedOutputStream(
        new FileOutputStream( args[2] )));
  
  try
  {
    int data;
    while ( true )
    {
      data = instr.readUnsignedByte() ;
      outstr.writeByte( data ) ;
    }
  }
  
  catch ( EOFException  eof )
  {
    outstr.close();
    instr.close();
    return;
  }
  
<span style="color:red;font-weight:bold">}</span>

</pre> 

<p>
The outer <code>try{}</code> block encloses the constructors and the 
IO loop.
</p>


</div>

<!-- QUESTION AREA -->
<div class="question">
<h3> QUESTION 18:</h3>
<a href="ch86_19.html">
<img src="../nextBut.gif" hspace="5" align="right" border="0"/></a>
<p>
What might go wrong inside the outer <code>try{}</code> block
which would cause an exception?
</p>

</div>

</body>
</html>
