<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html>
<head>
<meta name="copyright" content="2003,  Bradley Kjell" />
<meta name="author" content="Bradley Kjell kjell@ieee.org " />
<meta name="translation" content="Copyright 2004 Deutsche &Uuml;bersetzung Heinrich Gailer heinrich@gailer-net.de" />
<meta name="robots" content="index,follow" />
<title>Jede Methode in der Kette kann auffangen</title>
<link rel="stylesheet" type="text/css" href="../CAIstyle.css" />
</head>

<body>
<!-- generated by CSSmaker.java, version of 10/12/2004-->
<!-- from source javaChap81.frames on Wed Oct 24 11:17:05 CEST 2007 -->

<!-- ANSWER AREA -->

<div class="answer">
<h3>Eine gute Antwort w&auml;re:</h3>
<p>
Das Stack-Protokoll zeigt die Kette der Methodenaufrufe,
die zu demjenigen f&uuml;hren, der die Ausnahme verursacht hat,
ungef&auml;hr wie diese:
</p>

<pre class="code">
java.lang.IOException:  irgendeine Meldung
        at  irgendeine Java I/O-Methode
        at  SchwarzenPeterWeiterreichen.methodeC
        at  SchwarzenPeterWeiterreichen.methodeB
        at  SchwarzenPeterWeiterreichen.methodeA
        at  SchwarzenPeterWeiterreichen.main
</pre>

<p>
In einem tats&auml;chlichen Stack-Protokoll werden die Zeilennummern f&uuml;r jede
Methode aufgef&uuml;hrt.
</p>


</div>

<!-- LESSON AREA -->
<div class="lesson">
<h1>Jede Methode in der Kette kann auffangen</h1>

<p>
Jede Methode in der Kette der aufrufenden Methoden kann die Ausnahme auffangen.
Das folgende ist eine andere M&ouml;glichkeit das Programm zu organisieren:
</p>

<pre class="program">
public class SchwarzenPeterWeiterreichen
{

  public static void methodeC() <span style="color:red;font-weight:bold">throws IOException</span>
  {
     // einige I/O-Anweisungen
  }

  public static void methodeB() <span style="color:red;font-weight:bold">throws IOException</span>
  {
     methodeC();
  }

  public static void methodeA()
  {
     <span style="color:red;font-weight:bold">try</span>
     {
       methodeB();
     }
     <span style="color:red;font-weight:bold">catch ( IOException ex )</span>
     {
       // Anweisungen um die Ausnahme zu handhaben
     }

  }

  public static void main ( String[] a )
  {
     methodeA();
  }

}
</pre>


<p>
Eine Methode kann einige Ausnahmen behandeln und andere weiterreichen.
Einige der Ausnahmen, die sie behandelt, k&ouml;nnen ihren Ursprung in Methoden haben, die sie aufruft, andere k&ouml;nnen ihren Ursprung in ihr selbst haben.
Es kann so viele try/catch/finally-Strukturen in einer Methode geben wie notwendig sind.
Die Logik der Fehlerbehandlung von industriell erprobten Programmen
kann mehr Codezeilen ben&ouml;tigen als der "eigentliche" Zweck des Programms.
<!--The error handling logic of "industrial strength" programs
can take up more lines of code than the "real" purpose of
the Programm.-->
</p>

<p>
Eine Methode k&ouml;nnte mehrere Typen von gepr&uuml;ften Ausnahmen weiterreichen.
Ihre <code>throws</code>-Klausel sieht so aus:
</p>

<pre class="code">
throws ExceptionClass1, ExceptionClass2, ...
</pre>


<p>
Die Angabe von <b>ungepr&uuml;ften</b> Ausnahmen in einer <code>throws</code>-Klausel
ist optional.
</p>


</div>

<!-- QUESTION AREA -->
<div class="question">
<h3> FRAGE 8:</h3>
<a href="ch81_9.html">
<img src="../nextBut.gif" hspace="5" align="right" border="0"/></a>
<p>
(Ged&auml;chtnistest: ) Ist eine <code>ArithmeticException</code> eine gepr&uuml;fte Ausnahme?
</p>

</div>
<div>
<a title="Zurück zum Inhaltsverzeichnis gehen." href="../../java-toc.html#81">Inhaltsverzeichnis</a>
</div>

</body>
</html>
